version: "3.7"
services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/app/app
      - ./application.py:/app/application.py
      - ./main.py:/app/main.py
    env_file:
      - ./.env
    command: uvicorn main:app --host 0.0.0.0 --port 8989 --reload
    ports:
      - 8989:8989
